### ISSUE TITLE
关于反卷积层

### ISSUE THREAD

**Issue by wincle** [FlyingGoblin/CartoonGAN#4]
Hello，作者您好，我注意到你设计的网络中，每个反卷积层后都加了一层卷积层，这个卷积层是为了消除棋盘效应而设计的吗？

**Comment by FlyingGoblin** [comment]
是的。现在知道直接用upsampling+conv似乎会更好一些，但是由于我现在工作主要是不是做这个没有严谨的做实验验证

**Comment by FlyingGoblin** [comment]
是的。现在知道直接用upsampling+conv似乎会更好一些，但是由于我现在工作主要不是做这个，所以没有严谨的做实验验证

**Comment by wincle** [comment]
好的，谢谢，我来验证一下吧。

**Comment by wincle** [comment]
验证了下，确实用upsampling+conv会好一些，可惜发不了图片。
