### ISSUE TITLE
关于Gram矩阵

### ISSUE THREAD

**Issue by wincle** [FlyingGoblin/CartoonGAN#5]
Hi，论文里提了用8个 residual blocks 来做图像风格化，但是这真的很耗时，为什么当时没有考虑使用 gram 矩阵来做呢？谢谢~

**Comment by wincle** [comment]
在论文里找到答案了。

**Comment by wincle** [comment]
但是 residual blocks 真的很耗时，不知有什么优化的意见或替代方法？

**Comment by FlyingGoblin** [comment]
这个我倒是完全没有研究过0-0

**Comment by wincle** [comment]
有没有考虑过增加下采样层呢，这样后面的feature map可以小一些。

**Comment by FlyingGoblin** [comment]
好像做过实验但是效果不太好，但是我也不记得我做的3个下采样的实验是不是最终这个网络结构了

**Comment by wincle** [comment]
效果不好是指生成的图片卡通风格不强，还是与原图相比信息损失丢失严重呢？看论文里的网络是用了2个stride为2的卷积层实现的下采样，有没有试过pooling？

**Comment by FlyingGoblin** [comment]
不记得了，pooling没有试过

**Comment by ghzhangnj** [comment]
@wincle 能麻烦告知一下什么原因吗？

**Comment by SystemErrorWang** [comment]
> 有没有考虑过增加下采样层呢，这样后面的feature map可以小一些。

我试过用另外方法来做这个任务，用了4个residual block，base channel 32，整个模型不到10m，最后效果类似本文。感觉这种任务的模型大小比较随意，主要是loss的设计，以及训练的时候平衡g和d
